spring:
  application:
    name: DISCOVERY-SERVICE
server:
  port: 8761
eureka:
  instance:
    hostname: discovery-service
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
  response-cache-update-interval-ms: 5000
